# Generated by Django 6.1.2 on 2026-10-06 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_eui', models.CharField(max_length=31, unique=True, verbose_name='DevEUI')),
                ('nome', models.CharField(default='Sensor_Galpao_lab', max_length=100)),
                ('localizacao', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(db_index=True)),
                ('co_mq135', models.FloatField(verbose_name='CO (MQ - 135)')),
                ('co2_mq135', models.FloatField(verbose_name='CO2 (MQ - 135)')),
                ('nh4_mq135', models.FloatField(verbose_name='NH4 (MQ - 135)')),
                ('aceton_mq135', models.FloatField(verbose_name='Acetona (MQ - 135)')),
                ('alcool_mq135', models.FloatField(verbose_name='Alcool (MQ - 135)')),
                ('toluen_mq135', models.FloatField(verbose_name='Tolueno (MQ - 135)')),
                ('o3_mq131', models.FloatField(verbose_name='O3 (MQ - 131)')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='telemetria.sensornode')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ANOMALIA', 'Anomalia Detectada (Pico ou Falha)'), ('PREVISAO_CRITICA', 'Risco Futuro Previsto')], max_length=30)),
                ('mensagem', models.TextField()),
                ('resolvido', models.BooleanField(default=False)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Alertas', to='telemetria.sensornode')),
            ],
        ),
    ]
