# Generated by Django 6.1.2 on 2026-10-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airreading',
            name='nh4_mq135',
        ),
        migrations.AddField(
            model_name='airreading',
            name='mh4_mq135',
            field=models.FloatField(default=0.0, verbose_name='MH4 (MQ - 135)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensornode',
            name='criado_em',
            field=models.DateField(auto_now=True),
        ),
    ]
