# Generated by Django 6.1.2 on 2026-10-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0002_remove_airreading_nh4_mq135_airreading_mh4_mq135_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentalert',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='airreading',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sensornode',
            name='criado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
