# Generated by Django 6.1.2 on 2026-10-08 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0003_alter_agentalert_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentalert',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='telemetria.sensornode'),
        ),
        migrations.AlterField(
            model_name='agentalert',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sensornode',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='AgentPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('anomalia', models.BooleanField(default=False)),
                ('erro_reconstrucao', models.FloatField()),
                ('classe_iqar', models.CharField(max_length=30)),
                ('previsao_co', models.FloatField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes', to='telemetria.sensornode')),
            ],
        ),
    ]
